//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListaTelefonicaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefone
    {
        public int id { get; set; }
        public string ddd { get; set; }
        public string numero { get; set; }
        public int pessoa_id { get; set; }
    }
}
